name: Newman Run
on:
  push:
    branches: [ "master" ]

jobs:
  newman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create dir for report
        run: mkdir testArtifacts

      - name: Install Newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Run Test
        run: newman run ServRest.postman_collection.json -e serveRest_env.postman_environment.json -r cli,htmlextra

      - name: Report
        uses: actions/upload-artifact@v2
        with: 
            name: Reports
            path: newman
